### ISSUE TITLE
Codacy reports issue in code line

### ISSUE THREAD

**Issue by Paebbels** [pasztorpisti/py-flags#10]
Your GitHub integration Codacy [reports an issue](https://app.codacy.com/manual/pasztorpisti/py-flags/issues?&filters=W3siaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJDb2RlU3R5bGUiXX1d):

> **No value for argument 'value' in unbound method call**
> `bits, data = cls.flag_attribute_value_to_bits_and_data(name, data)`
>
> [goto source file](https://github.com/pasztorpisti/py-flags/blob/master/src/flags.py?ts=2#L436-L443)

Is this a valid issue?

**Comment by pasztorpisti** [comment]
It must be a bug in the static analyser used by codacy. Not uncommon, especially with dynamic languages that can be challenging to analyse.

That isn't an unbound method call because it is made with a `cls.` prefix (bound to the class object) and the call passes an argument for all method parameters.
