### ISSUE TITLE
Subclass with extended flags

### ISSUE THREAD

**Issue by madison-ookla** [pasztorpisti/py-flags#12]
Thanks for writing and maintaining this library! It seems exceptionally powerful for its use-case.

I'm curious if it's possible in any way to extend an already-defined `Flags` class. The documentation says otherwise, and I'm curious if there's something in the implementation that prohibits it beyond the `RuntimeError` that's raised. Here's an example:

```
class Vehicle(Flags):
    engine = 1
    tires = 2
    front_seats = 4


class PassengerCar(Vehicle):
    back_seats = 8


class Truck(Vehicle):
    truck_bed = 8
```

Would it be possible to accomplish something like this? In this particular case, the `Vehicle` class would never be used directly.

**Comment by pasztorpisti** [comment]
Hi @madison-ookla

Disallowing the extension of an already defined flags class was a deliberate design decision at the time of implementing the `flags` package. AFAIK, the standard `enum.IntFlags` class behaves in a similar way.

There are cases in which the "is a" relationship doesn't really work between your `PassengerCar` and `Vehicle`. Imagine a function that expects `Vehicle` flags as input and returns `PassengerCar`. What happens if someone passes `Truck` flags to that function? How the implementation of that function would look like?

In theory it could work but the function should be aware that this scenario exists (for example by explicitly casting the input flags to `Vehicle` or `int` or something similar). It would require more complicated type safety checks and auto-casts from the flags library with relaxed type-safety (that is a bad thing in my opinion).

The "flags subclassing" feature raises a lot of (or too many) questions similar to what I just explained. I wouldn't even be able to assemble a full list of potential problems off the top of my head and that's a very bad sign. (Remember the Zen of Python? "If the implementation is hard to explain, it's a bad idea.")

Flags subclassing introduces a lot of cognitive overhead when it comes to writing and reading/understanding code and would probably result in lots of bugs and unexpected runtime errors even with a lot of ("perfectly" implemented) runtime type checks in the flags package.

There can be many potential reasons why you want to use the proposed pattern.
The first couple of reasons that come to my mind:

1. You want flags inheritance: flags classes that have "is a" relationships with their bases.

   I already explained why this is a very bad idea that has lots of complications. The current flags implementation treats each flags class as its own type that is completely incompatible with every other flags class to avoid dealing with the enormous level of complexity that would be introduced by subclassing.

2. You want to avoid duplicated declaration of flag members but you don't need compatibility between flags classes even if they share some of their flag names-value pairs.

   In this case you could declare your flag values in pure python dicts (one dict for base class flags, one dict for each subclass, ....) and then you could create the actual flags classes with the
   `FlagsClass4 = FlagsClass3('FlagsClass4', dict(flag4=4, flag8=8))` syntax (copy-pasted from the `README.md` of this repo) or something like `MyFlagsClass = type('MyFlagsClass', (flags.Flags,), dict(member1=1, member2=2))` where `flags.Flags` could be replaced with your own customised flags base class.

   With some meta-programming skills you can implement this idea as a wrapper around the `flags` package (in the code base of the project that needs it) in a way that provides the subclassing syntax used in your original post but the resulting flags classes would still be provided by the `flags` package so they would be totally type incompatible without any inheritance. However, the duplication part would be solved.

If your project requires this kind of magic only in a few places then solving the problem in "shiny" ways is probably a waste of time. In that case I'd probably just copy-paste the flag members between the classes and would assume the existence of those flags in a few "magic" functions containing some hacky manual type-casts (to/from `int` values) and perhaps some runtime type checks instead of writing a "framework" to handle the situation.

**Comment by madison-ookla** [comment]
Thanks for the extremely thorough reply @pasztorpisti!

The exact scenario I find myself in is that I am building a Django-based UI for modifying database entries. There are a few distinct entities that can be edited through the app, but several of them use a integer field in the database to hold category flags. In a few of those cases, almost all of the flags are shared except for one of the higher bits (similar to the example I gave). My intention for asking the question was that I want to build Django machinery around handling the rendering of these flags in the UI as separate fields rather than just an `int`, allowing the user to alter the flags by checking boxes, and save any changes back to the database as an integer. My thought was that if I could provide a base class for the flags, I could 1) not repeat the common attributes and 2) have a common type to specify in the Django machinery. The reason I was hoping to accomplish this statically is because I'd prefer the assistance that a static type checker gives me when developing.

As I reflect on your response and the code I've written currently (I ended up implementing a flags class and machinery specific to only that flags class), I think there's a way to use the `BaseFlags` class you've defined in your example along with some specific typing to accomplish my goals. At the end of the day the Django machinery is the most important aspect to share, and I believe I should be able to do that with what the package offers now by creating base machinery subclasses that are then subclassed only to specify the flags class which should be used for the particular database entities that machinery interacts with. This approach feels more "Django-esque" to me anyway 😁 

I'll go ahead and close this now, as I think I've got the answers I need. Thank you again!

**Comment by pasztorpisti** [comment]
I'm happy that I could help. (Even if I couldn't provide a "perfect" solution but that isn't uncommon in software engineering. :-D)

Some extra thoughts regarding the problem you are solving:

Many SQL DBs have non-standard enum types. However, those are better to avoid in my opinion. Many people prefer storing enums as DB agnostic int values for practical reasons (e.g.: easier to modify the enum members, easier to copy the data to various DBs). It is possible to create a separate table for each enum type with columns (id/enum_value, name, description, whatever_you_need...) if you want to make the DB "self-describing" with some reflection/type-info. Multiple enums can be stored in a single table by adding an extra "enum_type" column. The same data-driven approach can be applied to your flags problem too if it makes sense in your situation. (It would not solve your duplication problem but I'd probably just copy-paste the duplicate members into each flags table.)

The benefits of the data driven approach (might or might not apply to your application):

- The flags metadata is available to all clients of the SQL DB (not only your python application). While using the same DB from multiple apps or scripts isn't necessarily a good idea (e.g.: micro-services deliberately avoid that), many existing systems use SQL DBs as interfaces between multiple apps (often written in different languages).
- The flags metadata can be edited (by the python app, or by any other SQL client) without modifying the source code.

It really depends on your situation whether an sql-data-driven or python-source-code driven approach is better. I just wanted to make sure that you are aware of the data-driven approach because quite a few systems I've seen could've benefited from it.

Getting back to your source-code based solution: if I had to avoid a lot of flags duplication in my python sources then I'd probably use something like this:

```python
#!/usr/bin/env python3
import collections

import flags


class CopiedFlagsMeta(type):
    def __call__(cls, *args, **kwargs):
        if not kwargs and len(args) == 3 and isinstance(args[1], tuple)\
                and len(args[1]) == 1 and isinstance(args[1][0], CopiedFlags):
            # "subclassing" an instance of CopiedFlags
            return cls.create_flags_class(args[0], args[2], args[1][0])
        # a call to CopiedFlags.__init__
        return super().__call__(*args, **kwargs)

    @staticmethod
    def create_flags_class(class_name, class_dict, copied_flags):
        for k in class_dict:
            if k in copied_flags.members:
                raise RuntimeError('class %r defines a duplicate member %r '
                                   'that exists in a copied flags base class' %
                                   (class_name, k))

        d = copied_flags.members.copy()
        d.update(class_dict)
        return type(copied_flags.base_class)(class_name, (copied_flags.base_class,), d)

    @classmethod
    def __prepare__(mcs, class_name, bases):
        return collections.OrderedDict()


class CopiedFlags(metaclass=CopiedFlagsMeta):
    def __init__(self, *flags_classes, base_class=None):
        assert all(issubclass(c, flags.Flags) for c in flags_classes)
        assert base_class is None or issubclass(base_class, flags.Flags)

        member_to_class = {}
        members = collections.OrderedDict()
        for clazz in flags_classes:
            for m in clazz:
                if m.name in members:
                    raise RuntimeError('Copied flag member %r is defined by both %r and %r' %
                                       (m.name, clazz, member_to_class[m.name]))
                member_to_class[m.name] = clazz
                members[m.name] = (int(m), m.data)

        if base_class is None:
            if flags_classes:
                base_class = flags_classes[0].__bases__[0]
            else:
                base_class = flags.Flags

        self.members = members
        self.base_class = base_class


class Vehicle(flags.Flags):
    engine = 1
    tires = 2
    front_seats = 4


class PassengerCar(CopiedFlags(Vehicle)):
    back_seats = 8


class Truck(CopiedFlags(Vehicle)):
    truck_bed = 8


print(list(Vehicle))
print(list(Truck))
print(list(PassengerCar))
```

The above code uses some meta-programming magic. Magic is bad, unless it makes your code simpler in a **LOT** of places in the codebase! If you don't have lots of duplications then use copy-paste or some other simple-stupid solution that is easier to understand than meta-programming.

The above trick results in something that is equivalent to this:

```python
#!/usr/bin/env python3
import flags


class Vehicle(flags.Flags):
    engine = 1
    tires = 2
    front_seats = 4


class PassengerCar(flags.Flags):
    engine = 1
    tires = 2
    front_seats = 4
    back_seats = 8


class Truck(flags.Flags):
    engine = 1
    tires = 2
    front_seats = 4
    truck_bed = 8


print(list(Vehicle))
print(list(Truck))
print(list(PassengerCar))
```

This means that the copy-paste has been eliminated by the trick but the `Vehicle`, `PassengerCar` and `Truck` flags are totally incompatible with each other. However, your code can exploit the known fact that all flag values of `Vehice` are the same in the "subclasses". With the `flags` package this exploit has to be done by casting both flag values to `int`, or by casting one of the flag values to `int` and then to the other flags type. E.g.:

```python
def has_engine(any_car_flags):
    return int(any_car_flags) & int(Vehicle.engine) == int(Vehicle.engine)


def has_engine_2(any_car_flags):
    return Vehicle.engine in Vehicle(int(any_car_flags))
```


Another thing I don't like about "dynamic" python magic (including the one I provided above) is that it often doesn't play well with static analyzers. In this respect meta-programming isn't necessarily worse than declaring flags with the (in my opinion weird) syntax I borrowed from the standard `enum` package: `DerivedClass = BaseClass('DerivedClass', 'flag0 flag1')`.

**Comment by madison-ookla** [comment]
Again I must say thank you for your thorough and thoughtful response! You do not need to convince me about a different solution on the database end - unfortunately the present case I'm dealing with is not a design decision I made. Since the database type is an integer, all of the logic has to be on the application end.

Your proposed solution is very slick! Based on our previous discussion though, I realized that my primary issue was that I needed machinery that could handle subclasses of `flags.Flags` the same way. These base classes would then be subclassed with the appropriate flags class for each application it was needed in. Here's some of the code I ended up with:

```python
from typing import TypeVar, Type
from flags import Flags


F = TypeVar('F', bound=Flags)


class BaseWidget:

    flags_class: Type[F] = None


    def some_func(self, value) -> F:
        return flags_class(value)
```

Then, later down the line I can have something like this:
```python
class SampleFlags(Flags):
    a = 1, "a"
    b = 2, "b"
    c = 4, "c"


class SampleFlagsWidget(BaseWidget):
    flags_class = SampleFlags

# This returns the appropriate SampleFlags class and plays nicely with static type checkers
SampleFlagsWidget().some_func(6)  # SampleFlags(b|c)
```

While I've only implemented one instance of this, I think it will be easy to carry this over to the other instances I have. The copying/redundancy of the flags themselves is much less of an issue than this shared machinery :)
